---
title: "flat_first.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

## Get a message with a number of rows
You can get a message with the number of rows in a data frame of interest with `get_df_nrows()`.

```{r development}
library(glue) # Au tout début
message("The dataset is composed of 150 observations")
nrow_df <- nrow(iris)
message(glue("The dataset is composed of {nrow_df} observations"))
```

# get_df_nrows
    
```{r function-get_df_nrows}
#' A very nice function
#' 
#' A function that returns the number of rows of a dataframe
#' 
#' @param df a dataframe
#' @importFrom glue glue
#'
#' @return a message
#' 
#' @export

get_df_nrows <- function(df){
    nrow_df <- nrow(df)
    message(glue("The dataset is composed of {nrow_df} observations"))
    return(nrow_df)
}
```
  
```{r example-get_df_nrows}
get_df_nrows(iris)
get_df_nrows(mtcars)
```
  
```{r tests-get_df_nrows}
test_that("get_df_nrows works", {
  expect_message(
    object = get_df_nrows(df = mtcars),
    regexp = "The dataset is composed of 32 observations"
  )
})
```

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_first.Rmd", vignette_name = "Minimal")
```
